package com.android.gandharvms.Outward_Truck_Dispatch;

public class Update_SmallPack_Model {

    public int Id ;
    public int OutwardId ;
    public String ilInTime ;
    public String ilOutTime ;
    public int ilpackof10ltrqty ;
    public int ilpackof18ltrqty ;
    public int ilpackof20ltrqty ;
    public int ilpackof26ltrqty ;
    public int ilpackof50ltrqty ;
    public int ilpackof210ltrqty ;
    public int ilpackofboxbuxketltrqty ;
    public String iltotqty ;
    public String ilweight ;
    public String ilsign ;
    public String ilRemark ;
    public String splInTime ;
    public String splOutTime ;
    public int splpackof7ltrqty ;
    public int splpackof7_5ltrqty ;
    public int splpackof8_5ltrqty ;
    public int splpackof10ltrqty ;
    public int splpackof11ltrqty ;
    public int splpackof12ltrqty ;
    public int splpackof13ltrqty ;
    public int splpackof15ltrqty ;
    public int splpackof18ltrqty ;
    public int splpackof20ltrqty ;
    public int splpackof26ltrqty ;
    public int splpackof50ltrqty ;
    public int splpackof210ltrqty ;
    public int splpackofboxbuxketltrqty ;
    public String spltotqty ;
    public String splweight ;
    public String splsign ;
    public String splRemark ;
    public boolean IsActive ;
    public String CreatedBy ;
    public String CreatedDate ;
    public String UpdatedBy ;
    public String UpdatedDate ;
    public String SerialNumber ;
    public String VehicleNumber ;
    public String TransportName ;
    public String MobileNumber ;
    public String CapacityVehicle ;
    public String ConditionOfVehicle ;
    public String Date ;
    public String MaterialName ;
    public String CustomerName ;
    public String OAnumber ;
    public int TankerNumber ;
    public String ProductName ;
    public int HowMuchQuantityFilled ;
    public String Location ;
    public char NextProcess ;
    public char I_O ;
    public String VehicleType ;
    public String PurposeProcess;

    public Update_SmallPack_Model(int outwardId, String splInTime, String splOutTime, int splpackof7ltrqty, int splpackof7_5ltrqty, int splpackof8_5ltrqty, int splpackof10ltrqty, int splpackof11ltrqty, int splpackof12ltrqty, int splpackof13ltrqty, int splpackof15ltrqty, int splpackof18ltrqty, int splpackof20ltrqty, int splpackof26ltrqty, int splpackof50ltrqty, int splpackof210ltrqty, int splpackofboxbuxketltrqty, String spltotqty, String splweight, String splsign, String splRemark, String updatedBy, char nextProcess, char i_O, String vehicleType , String purposeProcess) {
        OutwardId = outwardId;
        this.splInTime = splInTime;
        this.splOutTime = splOutTime;
        this.splpackof7ltrqty = splpackof7ltrqty;
        this.splpackof7_5ltrqty = splpackof7_5ltrqty;
        this.splpackof8_5ltrqty = splpackof8_5ltrqty;
        this.splpackof10ltrqty = splpackof10ltrqty;
        this.splpackof11ltrqty = splpackof11ltrqty;
        this.splpackof12ltrqty = splpackof12ltrqty;
        this.splpackof13ltrqty = splpackof13ltrqty;
        this.splpackof15ltrqty = splpackof15ltrqty;
        this.splpackof18ltrqty = splpackof18ltrqty;
        this.splpackof20ltrqty = splpackof20ltrqty;
        this.splpackof26ltrqty = splpackof26ltrqty;
        this.splpackof50ltrqty = splpackof50ltrqty;
        this.splpackof210ltrqty = splpackof210ltrqty;
        this.splpackofboxbuxketltrqty = splpackofboxbuxketltrqty;
        this.spltotqty = spltotqty;
        this.splweight = splweight;
        this.splsign = splsign;
        this.splRemark = splRemark;
        UpdatedBy = updatedBy;
        NextProcess = nextProcess;
        I_O = i_O;
        VehicleType = vehicleType;
        PurposeProcess = purposeProcess;
    }
}
